# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Tracking_App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 pod 'Surge', '~> 2.0.0'

end
